const items  = [
    {name: 'iphone', isWaste: true},
    {name: 'android', isWaste: false},
    {name: 'minecraft', isWaste: false},
    {name: 'github', isWaste: 'free'},
    {name: 'ethan burks', isWaste: true},
    {name: 'william egolf', isWaste: true},
    {name: 'noah pytlowanyj', isWaste: true},
    {name: 'air', isWaste: 'free'},
    {name: 'https', isWaste: 'custom', custom: 'depends', explanation: 'hehe repl'},
    {name: 'mariah bourzac', isWaste: 'custom', custom: 'mariah is annoying sometimes'},
    {name: 'roman russo', isWaste: true, explanation: 'he is kinda annoying'},
    {name: 'this website', isWaste: 'custom', custom: 'how dare you check if this website is a waste of money!! its free how could it possibly be???'},
    {name: 'optifine', isWaste: 'free'},
    {name: 'optifine cape', isWaste: false},
    {name: 'samsung', isWaste: true},
    {name: 'google', isWaste: 'free'},
    {name: 'robux', isWaste: true},
    {name: 'minecraft bedrock', isWaste: true},
    {name: 'fortnite', isWaste: 'free', explanation: 'but... this <i>is</i> fortnite soooo.... maybe thats not so true'},
    {name: 'money', isWaste: true},
    {name: 'netflix', isWaste: true},
    {name: 'hulu', isWaste: true},
    {name: 'youtube red', isWaste: true},
    {name: 'humble bundle', isWaste: true},
    {name: 'pizza', isWaste: 'custom', custom: 'never', explanation: 'unless it is a <a href="https://i.pinimg.com/originals/3a/be/70/3abe70be046eed475708ee9b0dd21179.jpg">golden pizza</a>'},
    {name: 'testing', isWaste: true, explanation: 'testing is a waste of time and time is money.'},
    {name: 'terraria', isWaste: false, explanation: 'its kinda like minecraft and minecraft is good so no not a waste'},
    {name: 'faithful', isWaste: 'custom', custom: 'depends'},
    {name: 'css', isWaste: 'true', explanation: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'},
    {name: 'water', isWaste: 'custom', custom: 'depends', explanation: 'it really depends on a lot of things'},
    {name: 'toilet paper', isWaste: true, explanation: 'welcome to 2020'},
    {name: 'i', isWaste: true},
    {name: 'my life', isWaste: true},
    {name: 'pain', isWaste: 'custom', custom: 'depends', explanation: 'what kind of pain are you talking about? bread is not a waste of money'},
    {name: 'infinite pain', isWaste: 'free', explanation: 'even though this is free i\'d say its still a waste of free'},
    {name: 'video games', isWaste: 'custom', custom: 'depends', explanation: 'video games is too general i need more than just video games how am i supposed to tell you if all video games are a waste of money?? some are even free so i dont understand what is your problem???'},
    {name: 'minecraft dungeons', isWaste: false},
    {name: 'internet', isWaste: false},
    {name: 'seus ptgi', isWaste: 'custom', custom: 'anyone know what that is?!'},
    {name: 'apple pro stand', isWaste: true, explanation: 'A MONITOR STAND FOR 999$?!? ARE YOU FOR REAL, IT DEFINITELY IS A WASTE OF MONEY REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE'},
    {name: 'microtransactions in mobile games', isWaste: true},
    {name: 'minecraft 3ds', isWaste: true},
    {name: 'life', isWaste: 'custom', custom: 'depends', explanation: 'If you mean your life, totally, but life in general ... well, I guess, living stuff created money and also ways to waste it, so ... kinda ...'},
    {name: 'jabin nibbelink', isWaste: false, explanation: 'creator of this website. therefore, not a waste of money. also, this is a fork of "is.wasteof.money" by jeffalo, so thanks to him as well.'},
    {name: 'scratch', isWaste: 'custom', custom: 'scratch is free, but they beg for "donates" (thanks to mybearworld lol) also, no, scratch is not a waste of money. thanks for coming to my website.'},
    {name: 'guinea pig', isWaste: false, explanation: 'well, mariah said so, so i had to put it in as false. try "mariah bourzac"'}
];
